language: node_js

node_js:
  - "stable"

cache:
  yarn: true

branches:
  only:
    - master

before_install:
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - yarn global add codeclimate-test-reporter

script:
  - yarn install
  - yarn run linter
  - yarn run test:travis
  - yarn run build:prod

after_success:
  - codeclimate-test-reporter < coverage/lcov.info
