language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0

script:
  - yarn install
  - yarn run build:prod
